name: Auto Push Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  auto-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "Auto commit changes [skip ci]"
          git push 